### ISSUE TITLE
configure:error: Cannot find OpenSSL's <evp.h>

### ISSUE THREAD

**Issue by Amgine0** [kasparsd/php-7-debian#1]
Clean install debian 8.2.0 amd64
install git, clone, run ./build.sh:

``` bash
configure: error: Cannot find OpenSSL's <evp.h>
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
```

**Comment by kasparsd** [comment]
@Amgine0 Try installing `libssl-dev` to see if that fixes the issue:

```
$ sudo apt-get install libssl-dev
```

**Comment by Amgine0** [comment]
Same results after installing libssl-dev.

``` bash
configure: error: Cannot find OpenSSL's libraries
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
```

(well, slightly different, but...)

**Comment by PyRowMan** [comment]
Same issue here :/

#### EDIT :

Resolved with : 

>  sudo apt-get install libcurl4-openssl-dev pkg-config.

**Comment by kasparsd** [comment]
Thanks @PyRowMan!

**Comment by icamys** [comment]
Don't forget to run:

```
sudo apt-get update
```

before trying to install new packages.
