### ISSUE TITLE
ERROR: cannot verify pear.php.net's certificate

### ISSUE THREAD

**Issue by dvpusha** [kasparsd/php-7-debian#12]
Thank you for this script!
After trying

> $ ./build.sh

I get the error:

> ERROR: cannot verify pear.php.net's certificate, issued by ‘/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA’:
>   Unable to locally verify the issuer's authority.
> To connect to pear.php.net insecurely, use `--no-check-certificate'.

What am I doing wrong?

**Comment by kasparsd** [comment]
@iliaxone I'm getting the same error. It looks like Debian doesn't like the certificate chain sent by pear.php.net. Haven't found a proper solution yet.

**Comment by dvpusha** [comment]
@kasparsd And...How to install PHP 7? :)

**Comment by kasparsd** [comment]
@iliaxone A simple fix is to add `--without-pear` to the configuration options.
