### ISSUE TITLE
Freetype Support

### ISSUE THREAD

**Issue by iRbouh** [kasparsd/php-7-debian#14]
Could you please add the gd FreeType support. 

libfreetype6-dev 
--with-freetype-dir

Best Regards.

**Comment by kasparsd** [comment]
@iRbouh What is your particular use-case for FreeType?

**Comment by aoloe** [comment]
calculating the size of text when using GD...

**Comment by aoloe** [comment]
"endroid/qrcode" does use it, and my very cheap shared hosting provider has it enabled...

**Comment by redridingreaper** [comment]
Hi Kaspars, has the support for freetype been added yet?

I try to compile with   --with-freetype-dir=/usr/include/freetype2

But still no support for freetype functions in GD

**Comment by kasparsd** [comment]
@redridingreaper You could try adding it to the config here:

https://github.com/kasparsd/php-7-debian/blob/8f96811c745a439826a5e6eb9bae109ffbb0badd/build.sh#L37-L72

Not sure if it requires any additional system libraries to be enabled.

**Comment by redridingreaper** [comment]
> @redridingreaper You could try adding it to the config here:
> 
> Not sure if it requires any additional system libraries to be enabled.

I did exactly like this :(

Same thing with "--with-imap"

**Comment by redridingreaper** [comment]
Apparently you need to include imap-ssl and kerberos too in build.sh config string and make a fresh build:
--with-imap \
--with-imap-ssl \
--with-kerberos \

Now it works.

 Also solved the problem with the lack of freetype functions in GD by adding:
--with-freetype-dir=/usr/include/freetype2 \

**Comment by kasparsd** [comment]
Thanks for posting an update on the config that worked @redridingreaper!
