### ISSUE TITLE
Set php 7 a default

### ISSUE THREAD

**Issue by H-E-X** [kasparsd/php-7-debian#15]
Hi,

Thanks for this script, it works perfectly, but I have some problems. I want to install pthreads with pecl, but is still wants to use php 5.6. How can I set php 7 as the default version, so pecl install and cli php will use that.

Thanks!

**Comment by kasparsd** [comment]
@H-E-X The readme file has an example for building the Memcached extension:

```
$ /usr/local/php7/bin/phpize
$ ./configure --with-php-config=/usr/local/php7/bin/php-config
$ make
$ sudo make install
```

It appears that pthreads is almost ready for PHP7 https://github.com/krakjoe/pthreads
