### ISSUE TITLE
Run install.sh as root

### ISSUE THREAD

**Issue by zupolgec** [kasparsd/php-7-debian#18]
I had to run `install.sh` as root with sudo. Is this a problem of my Debian configuration, or is that a common issue?

**Comment by kasparsd** [comment]
I'm not sure @zupolgec. I wonder what are the default permissions for `/usr/local`

> By default, the owner and group of /usr/local and all subdirectories (including bin) should be root.root and the permissions should be rwxr-xr-x.

from http://unix.stackexchange.com/a/37726/148970

**Comment by zupolgec** [comment]
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=538392:

> The '/usr/local' directory itself and all the subdirectories created by the package should (by default) have permissions 2775 (group-writable and set-group-id) and be owned by `root.staff'.

It seems that the staff group is empty by default. So I think the `install.sh` should be executed as root (or with sudo).

**Comment by kasparsd** [comment]
@zupolgec Yeah, that sounds right. Can you update the readme?
