### ISSUE TITLE
error: memcached support requires libmemcached

### ISSUE THREAD

**Issue by sirmbhe** [kasparsd/php-7-debian#2]
Hello,

Thank you for the script. I manage to get it work, but facing some problem when i want to install memcached.

When executing this command : ./configure --with-php-config=/usr/local/php7/bin/php-config

I get this kind of error :

checking for libmemcached location... configure: error: memcached support requires libmemcached. Use --with-libmemcached-dir=<DIR> to specify the prefix where libmemcached headers and library are located

Any idea how to solve it?
Thanks

**Comment by razvanphp** [comment]
You can try `sudo apt-get install libmemcached-dev libmemcached11`
