### ISSUE TITLE
Add support for Redis

### ISSUE THREAD

**Issue by ahansson89** [kasparsd/php-7-debian#22]
This is what I am doing now to enable redis:

git clone https://github.com/phpredis/phpredis.git && \
    cd phpredis && \
    git checkout php7 && \
    phpize && \
    ./configure && \
    make && make install && \
    cd .. && \
    rm -rf phpredis && \
    #activate phpredis
    echo "extension=redis.so" > /etc/php/mods-available/redis.ini && \
    ln -sf /etc/php/mods-available/redis.ini /etc/php/7.0/fpm/conf.d/20-redis.ini && \
    ln -sf /etc/php/mods-available/redis.ini /etc/php/7.0/cli/conf.d/20-redis.ini

Would be awesome if it could be added to this repo

**Comment by kasparsd** [comment]
I would prefer to leave all the 3rd party extensions outside the core build. Maybe you could add this to the readme file [where we already have something similar for Memcached](https://github.com/kasparsd/php-7-debian#installing-memcached-extension).

**Comment by ahansson89** [comment]
Added PR for that
