### ISSUE TITLE
libxslt is missing in dependencies list

### ISSUE THREAD

**Issue by tim-bezhashvyly** [kasparsd/php-7-debian#27]
While installing on debian/jessie64:

> configure: error: xslt-config not found. Please reinstall the libxslt >= 1.1.0 distribution

**Comment by tim-bezhashvyly** [comment]
Found out that it was caused because I have added `--with-xsl` to configuration string. If you feel it is not worthy to add `libxml2-dev` to dependencies sure close this issue and PR.

**Comment by kasparsd** [comment]
Yeah, that sounds like it. Thanks @tim-bezhashvyly!
