### ISSUE TITLE
Run client script

### ISSUE THREAD

**Issue by clarkk** [kasparsd/php-7-debian#31]
How to run PHP as `cli` ??

```
/usr/local/php7/sbin/php7-fpm -f /var/cronjob.php
```

**Comment by clarkk** [comment]
```
/usr/local/php7/bin/php -f /var/cronjob.php
```

**Comment by maximal** [comment]
You can go without `-f`, just:

``` sh
/usr/local/php7/bin/php /var/cronjob.php
```

**Comment by stathis** [comment]
You can even create a symlink so you can omit the whole path every time you need to run the php7 cli.
`ln -s /usr/local/php7/bin/php /usr/bin/php7`
