### ISSUE TITLE
imap support

### ISSUE THREAD

**Issue by clarkk** [kasparsd/php-7-debian#32]
How to build PHP with IMAP support?

The extension is not under `/usr/local/php7/include/php/ext`

**Comment by kasparsd** [comment]
Should be similar to how it's done for [Memcached](https://github.com/kasparsd/php-7-debian#installing-memcached-extension), for example.

**Comment by clarkk** [comment]
but what about the dependencies?!

**Comment by kasparsd** [comment]
@clarkk Actually, you just need to edit the build configuration in `build.sh`, see http://php.net/manual/en/imap.installation.php

**Comment by clarkk** [comment]
Solution

https://forum.directadmin.com/showthread.php?t=45434
http://www.brighterlamp.com/2012/12/how-to-compile-php-with-imap-support/

```
apt-get install libpam0g-dev
cd /usr/local && wget ftp://ftp.cac.washington.edu/imap/imap-2007f.tar.gz && tar -xvf imap-2007f.tar.gz && cd imap-2007f
make lr5 && mkdir lib && mkdir include
cp c-client/*.c lib/ && cp c-client/*.h include/ && cp c-client/c-client.a lib/libc-client.a
```

Add to build.sh

```
--with-imap-ssl=/usr/local/imap-2007f \
--with-imap=/usr/local/imap-2007f \
```
