### ISSUE TITLE
Upstart not working on Ubuntu

### ISSUE THREAD

**Issue by jakejackson1** [kasparsd/php-7-debian#4]
Great installer script you've got.

Once issue I'm having is the php7-fpm service isn't available when using sudo. For instance, I can type in `php7-fpm` on the command line and it will attempt to execute but doesn't have the correct privileges. As soon as I run `sudo php7-fpm`, or login as root and do the same it says command not found. Any ideas?

**Comment by kasparsd** [comment]
There is a [Zend PHP7 repo](http://php7.zend.com/repo.php) for Ubuntu.

Please let me know if you learn about the specific requirements for Upstart.

**Comment by jakejackson1** [comment]
Thanks.
