### ISSUE TITLE
Error compiling with openssl 1.1.0

### ISSUE THREAD

**Issue by Cojad** [kasparsd/php-7-debian#41]
https://bugs.php.net/bug.php?id=72360

Maybe we should inform user if system has openssl 1.1.0 headers and use the php7/master for temporary solution?

**Comment by Cojad** [comment]
It's possible to use below command on Debian 8 (jessie) to downgrade libssl-dev to 1.0.1t.
Then it will compile without problem.
```bash
apt-ge install libssl-dev=1.0.1t-1+deb8u5
```

**Comment by andrewhood125** [comment]
@Cojad on my default install of Debian 8.7 I have 1.0.1t by default. 

```
root@debian-512mb-nyc1-01:~# openssl version
OpenSSL 1.0.1t  3 May 2016
```

**Comment by kasparsd** [comment]
Thank you @Cojad! Closing this since you provided a solution.
