### ISSUE TITLE
Doubt about compiling with shared mode libraries

### ISSUE THREAD

**Issue by dertin** [kasparsd/php-7-debian#48]
What is the difference?

--with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-openssl ...
or
--with-mysqli=shared,mysqlnd --with-pdo-mysql=shared,mysqlnd --with-openssl=shared ...

Previously compile OpenSSL 1.1.0f, zlib 1.2.11, libssh2 1.8.0, Nghttp2 1.23.1,  curl 7.54.1, MariaDB 10.2.6.
[In my script under construction](https://gist.github.com/dertin/8de14e458dd4f0d3acb5f0deff120951)

I have compiled in shared mode the libraries.

I do not understand much about the topic, but I would like the php compilation use the latest versions of the compiled libraries

You can also look: [PHP 5.3 shared mode configure](https://gist.github.com/flaudisio/4070059#file-php-5-3-shared-configure-sh)

I appreciate your help.

**Comment by kasparsd** [comment]
I'm not sure @dertin :) What is the use-case for shared libraries?
