### ISSUE TITLE
how to enable GMP module in php7.2

### ISSUE THREAD

**Issue by hqin2013** [kasparsd/php-7-debian#57]
hi,

I have finished the install ,this script is great!

but my composer install tips me need GMP module enabled,any suggestion?! i checked the php.ini & search in Google,can't find a solution.or the gmp module can't compatible with php7.2?!

Regards
Qin

**Comment by kasparsd** [comment]
@hqin2013 Looks like you might need to edit `build.sh` to [include the `--with-gmp` option](http://php.net/manual/en/gmp.installation.php). For example, add `--with-gmp \` right after `--with-gd \` in line 49.

**Comment by kasparsd** [comment]
And you might need the `libgmp-dev` package for this to work.
