### ISSUE TITLE
On Debian 7.6 x86 installing stops with error

### ISSUE THREAD

**Issue by spendmail** [kasparsd/php-7-debian#59]
1) **./configure "$CONFIGURE_STRING"** returns:
Notice: Following unknown configure options were used:
--with-mcrypt
--with-mysql=mysqlnd
--with-fpm-user=www-data
--with-fpm-group=www-data'
Check './configure --help' for available options

2) **make install** returns:
Installing shared extensions:     /usr/local/php7 --enable-huge-code-pages --with-config-file-scan-dir=/usr/local/php7/etc/conf.d --enable-bcmath --with-bz2 --enable-calendar --enable-intl --enable-exif --enable-dba --enable-ftp --with-gettext --with-gd --with-jpeg-dir --enable-mbstring --with-mcrypt --with-mhash --enable-mysqlnd --with-mysql=mysqlnd --with-mysql-sock=/var/run/mysqld/mysqld.sock --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-openssl --enable-pcntl --with-pspell --enable-shmop --enable-soap --enable-sockets --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-wddx --with-zlib --enable-zip --with-readline --with-curl --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data/lib/php/extensions/no-debug-non-zts-20170718/
cp: unrecognized option '--with-fpm-group=www-data/lib/php/extensions/no-debug-non-zts-20170718/#INST@24415#'
Try `cp --help' for more information.
make: *** [install-modules] Error 1

What could it be?

**Comment by hranicka** [comment]
This could be the reason: https://github.com/kasparsd/php-7-debian/commit/27890f61a81e909bde003e213b3a09a67d082ed5#diff-0b83f9dedf40d7356e5ca147a077acb4R77

Try to build when you remove the quotes there.
