### ISSUE TITLE
[Advice] - when upgrading between PHP tags

### ISSUE THREAD

**Issue by wkhayrattee** [kasparsd/php-7-debian#60]
Hi.. this is not a bug report, but a trivial support question..

Let's say I need to move from php 7.1.2 to php 7.1.5 for example, how do I need to proceed?
Should I re-run the all the `build.sh` and `install.sh` again and again for successive new releases?

Asking because inside the `build.sh` script I cannot see any code block which caters for that. Each run is a _new run_.

Thanks

**Comment by kasparsd** [comment]
@7php That is a great question and we should probably add it to the `readme.md`.

I just run `./build.sh`. There is no need for `./install.sh` since the config files don't normally change.
