### ISSUE TITLE
Remove 'with-mcrypt' - it's deprecated since PHP 7.1

### ISSUE THREAD

**Issue by wkhayrattee** [kasparsd/php-7-debian#61]
Hi,
when compiling I get the following warning: `configure: WARNING: unrecognized options: --with-mcrypt`.

It makes sense as mcrypt is deprecated since PHP 7.1. You might want to consider removing that line.

cheers

**Comment by kasparsd** [comment]
Thanks for reporting the issue @7php! This should be fixed in #56.

**Comment by kasparsd** [comment]
Closing as duplicate of #55.
