### ISSUE TITLE
Issue with process

### ISSUE THREAD

**Issue by borisjourdan** [kasparsd/php-7-debian#62]
Hi and sorry for my english (I'm french).

I follow all step to install php7

I'm on a Debian Wheezy whith Apache 2.2 installed.

It seems to be working but apache is still using the old version (php 5.6.35) even after restart.

how can i say apache to use php7 and not the old version ?

Thanks by advance.

**Comment by kasparsd** [comment]
Sorry, I really don't know. Maybe others with Apache experience can chime in here.
