### ISSUE TITLE
Why I have not php7-fpm in /etc/init.d/ folder?

### ISSUE THREAD

**Issue by easyyu** [kasparsd/php-7-debian#64]
I did it successfuly the compile of code..
But I have not in init.d start-stop script.
Why?

**Comment by kasparsd** [comment]
@easyyu Did you run `sudo ./install.sh` after building the code?

**Comment by easyyu** [comment]
Ahh..
After 2h of building, compailing, I simply forgot.
Thx for suggestion, that was the problem!
