### ISSUE TITLE
php7-fpm service: connection with Apache 2 / mod_proxy_fcgi failed

### ISSUE THREAD

**Issue by francoisjacquet** [kasparsd/php-7-debian#9]
Thank you for this script. I was able to install PHP7.

Trying to configure Apache 2, I have followed this [tutorial](https://wiki.apache.org/httpd/PHP-FPM) making use of `mod_proxy_fcgi`.

Here is the Apache 2 `error.log`:

```
[proxy:error] [pid 16302] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9007 (*) failed
[Mon Dec 07 12:56:52.484892 2015] [proxy_fcgi:error] [pid 16302] [client ::1:60787] AH01079: failed to make connection to backend: 127.0.0.1
```

And the php7-fpm service status:

```
php7-fpm.service - LSB: starts php7-fpm
   Loaded: loaded (/etc/init.d/php7-fpm)
   Active: active (exited) since Mon 2015-12-07 12:50:03; 54min ago
  Process: 16106 ExecStop=/etc/init.d/php7-fpm stop (code=exited, status=0/SUCCESS)
  Process: 15408 ExecReload=/etc/init.d/php7-fpm reload (code=exited, status=0/SUCCESS)
  Process: 16114 ExecStart=/etc/init.d/php7-fpm start (code=exited, status=0/SUCCESS)
```

I am not sure the service should report `active (exited)`?...

**Comment by kasparsd** [comment]
Yes, that looks right, it should be running. You can check `top` to see if `php-fpm` is there.

Try following these instructions here https://github.com/cookiecavekeeper/php7_apache_ubuntu_setup#setting-up-apache-with-php-fpm

You might have better luck rebuilding it with `--with-apxs2` and using it as an Apache module instead.

**Comment by francoisjacquet** [comment]
Please note that the php7-fpm process did not appear in the process list: `ps -C php7-fpm`

Alright, for info, after adding the `php7-fpm.service` file to `/lib/systemd/system`:

```
[Unit]
Description=php7-fpm

[Service]
Type=forking
ExecStart=/usr/local/php7/sbin/php7-fpm

[Install]
WantedBy=multi-user.target
```

I was able to debug the `www.conf` file using the `sudo systemctl status php7-fpm` command:
Use `listen = 127.0.0.1:9007` and **NOT** `listen 127.0.0.1:9007` as mentioned in some tutorials!

Thanks for your help!

**Comment by kasparsd** [comment]
Thanks for reporting your findings @francoisjacquet!

> after adding the php7-fpm.service file to /lib/systemd/system

Looks like this is specific to Ubuntu, right?

**Comment by francoisjacquet** [comment]
Nope, this is for Debian Jessie.

**Comment by kasparsd** [comment]
I see, thanks.

Were you able to use the included init script?

```
$ /etc/init.d/php7-fpm {start|stop|status|restart|reload|force-reload}
```

**Comment by francoisjacquet** [comment]
Yes, the init script is working fine.
The proper `systemd` method was only helpful for me to have those error messages indicating which lines of the config files were wrong:

```
$ sudo systemctl status php7-fpm
● php7-fpm.service - php7-fpm
   Loaded: loaded (/lib/systemd/system/php7-fpm.service; enabled)
   Active: failed (Result: exit-code) since Mon 2015-12-07 14:32:56; 4s ago
  Process: 17895 ExecStart=/usr/local/php7/sbin/php7-fpm (code=exited, status=78)

Dec 07 14:32:56 debian php7-fpm[17895]: [07-Dec-2015 14:32:56] ERROR: [/usr/local/php7/etc/php-fpm.d/www.conf:6] value is NULL f...R_ENTRY
Dec 07 14:32:56 debian php7-fpm[17895]: [07-Dec-2015 14:32:56] ERROR: Unable to include /usr/local/php7/etc/php-fpm.d/www.conf f... line 6
Dec 07 14:32:56 debian php7-fpm[17895]: [07-Dec-2015 14:32:56] ERROR: failed to load configuration file '/usr/local/php7/etc/php-fpm.conf'
Dec 07 14:32:56 debian php7-fpm[17895]: [07-Dec-2015 14:32:56] ERROR: FPM initialization failed
Dec 07 14:32:56 debian systemd[1]: php7-fpm.service: control process exited, code=exited status=78
Dec 07 14:32:56 debian systemd[1]: Failed to start php7-fpm.
Dec 07 14:32:56 debian systemd[1]: Unit php7-fpm.service entered failed state.
```

So I would prefer systemd over the "old" method.
